pimcore:
    objects:
        select_options:
            definitions:
                AirportType:
                    id: AirportType
                    group: null
                    useTraits: ''
                    implementsInterfaces: ''
                    selectOptions: {  }
