pimcore:
    objects:
        select_options:
            definitions:
                Surface:
                    id: Surface
                    group: null
                    useTraits: ''
                    implementsInterfaces: ''
                    selectOptions: {  }
