pimcore_data_hub:
    configurations:
        airport_runway:
            general:
                active: true
                type: dataImporterDataObject
                name: airport_runway
                description: ''
                group: 'AP relations'
                path: null
                modificationDate: 1733141993
                createDate: 1733140427
            loaderConfig:
                type: asset
                settings:
                    assetPath: /runways_lm.csv
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: airport
                loadingStrategy:
                    type: attribute
                    settings:
                        dataSourceIndex: '2'
                        attributeName: ident
                        language: ''
                        includeUnpublished: true
                createLocationStrategy:
                    type: doNotCreate
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: noChangeUnpublishNew
            processingConfig:
                executionType: parallel
                idDataIndex: ''
            mappingConfig:
                -
                    label: 'new column'
                    dataSourceIndex:
                        - '0'
                    settings:
                        loadStrategy: attribute
                        attributeDataObjectClassId: runway
                        attributeName: runwayId
                        attributeLanguage: ''
                        loadUnpublished: 'on'
                    transformationResultType: dataObjectArray
                    dataTarget:
                        type: manyToManyRelation
                        settings:
                            fieldName: runway
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                            overwriteMode: merge
                    transformationPipeline:
                        -
                            type: asArray
                        -
                            settings:
                                loadStrategy: attribute
                                attributeDataObjectClassId: runway
                                attributeName: runwayId
                                attributeLanguage: ''
                                loadUnpublished: 'on'
                            type: loadDataObject
            executionConfig:
                scheduleType: recurring
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
