pimcore_data_hub:
    configurations:
        runway:
            general:
                active: true
                type: dataImporterDataObject
                name: runway
                description: ''
                group: ''
                path: null
                modificationDate: 1733170473
                createDate: 1732828452
            loaderConfig:
                type: asset
                settings:
                    assetPath: /Arkusz2.csv
            interpreterConfig:
                type: csv
                settings:
                    skipFirstRow: true
                    delimiter: ','
                    enclosure: '"'
                    escape: \
            resolverConfig:
                elementType: dataObject
                dataObjectClassId: runway
                loadingStrategy:
                    type: attribute
                    settings:
                        dataSourceIndex: '0'
                        attributeName: runwayId
                        language: ''
                        includeUnpublished: true
                createLocationStrategy:
                    type: staticPath
                    settings:
                        path: /Runway
                locationUpdateStrategy:
                    type: noChange
                publishingStrategy:
                    type: noChangeUnpublishNew
            processingConfig:
                executionType: parallel
                idDataIndex: ''
            mappingConfig:
                -
                    label: 'id [0]'
                    dataSourceIndex:
                        - '0'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: runwayId
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: 'airport_ref [1]'
                    dataSourceIndex:
                        - '1'
                    transformationResultType: numeric
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: airportRef
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: numeric
                -
                    label: 'airport_ident [2]'
                    dataSourceIndex:
                        - '2'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: airportIdent
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'length_ft [3]'
                    dataSourceIndex:
                        - '3'
                    settings:
                        unitSourceSelect: static
                        staticUnitSelect: ft
                    transformationResultType: quantityValue
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: lengthFt
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                unitSourceSelect: static
                                staticUnitSelect: ft
                            type: quantityValue
                -
                    label: 'width_ft [4]'
                    dataSourceIndex:
                        - '4'
                    settings:
                        unitSourceSelect: static
                        staticUnitSelect: ft
                    transformationResultType: quantityValue
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: widthFt
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            settings:
                                unitSourceSelect: static
                                staticUnitSelect: ft
                            type: quantityValue
                -
                    label: 'surface [5]'
                    dataSourceIndex:
                        - '5'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: surface
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
                -
                    label: 'lighted [6]'
                    dataSourceIndex:
                        - '6'
                    transformationResultType: boolean
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: lighted
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: boolean
                -
                    label: 'closed [7]'
                    dataSourceIndex:
                        - '7'
                    transformationResultType: boolean
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: closed
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline:
                        -
                            type: boolean
                -
                    label: key
                    dataSourceIndex:
                        - '0'
                    transformationResultType: default
                    dataTarget:
                        type: direct
                        settings:
                            fieldName: key
                            language: ''
                            writeIfTargetIsNotEmpty: true
                            writeIfSourceIsEmpty: true
                    transformationPipeline: {  }
            executionConfig:
                scheduleType: recurring
                cronDefinition: ''
                scheduledAt: ''
            permissions:
                user: {  }
                role: {  }
            workspaces: {  }
